project:
  type: website
  output-dir: docs
  resources:
    - google1234567890abcdef.html

website:
  title: "Jesica Formoso"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: posts.qmd
        text: Posts
      - href: talks.qmd
        text: Talks/workshops
      - href: cv.qmd
        text: CV
    right:
      - icon: github
        href: https://github.com/jformoso/
        aria-label: GitHub
      - icon: linkedin
        href: https://www.linkedin.com/in/jesica-formoso-16ab4649/
      - icon: twitter
        href: https://twitter.com/JesiFormoso/
      - text: "{{< ai orcid >}}"
        href: https://orcid.org/0000-0003-3062-4036



format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

babelquarto:
  languagelinks: navbar
  languagecodes:
  - name: es
    text: ""
  - name: en
    text: ""
  mainlanguage: 'en'
  languages: ['es']
title-es: title in es
description-es: description in es
author-es: author in es
lang: en




